### ISSUE TITLE
op2 Roadmap

### ISSUE THREAD

**Issue by mmastrac** [denoland/deno_core#22]
- [x] Fastcall support for v8::* (this does work!) (#25)
 - [x] In/out buffers
   - [x] &[u8] (#33) 
   - [x] JsBuffer et al (for async) (#60)
 - [x] OpState support (#28)
   - [x] #[state] arguments that automatically read OpState (Rc, &, &mut) (#29)
 - [x] async ops (#40) (#54)
    - [ ] HandleScope support in async ops (possible - needs design)
    - [x] op tracker
    - [x] ~Ensure `Rc<RefCell<OpState>>` is only available for async ops~ (will not do this)
 - [x] external/cvoid mapping (https://github.com/denoland/deno_core/pull/146)
 - [ ] Check error handling and error types for advanced argument types
 - [x] #[global] v8::Global support (#58)
- [ ] fast async ops #147 

Nice to haves:

 - [ ] #[resource] arguments that automatically read the resource table (Rc, &, &mut)
 - [ ] Fastcall detection argument (`#[is_fast] bool`?)
 - [ ] #[op(turbo)] for ops that don't touch any of the slow paths (ie: no state, no context, no scope)
 - [ ] Port #[op(wasm)] from op1

**Comment by bartlomieju** [comment]
Let's lower the priority on this issue - it appears we have all the ingredients now to start migrating ops in `deno` to use `op2`.

**Comment by mmastrac** [comment]
Closing this bug for now -- followup bugs tracking the rest of the progress.
