### ISSUE TITLE
Async op performance roadmap

### ISSUE THREAD

**Issue by mmastrac** [denoland/deno_core#296]
- [ ] unrefOp -> unrefPromise to avoid complex accounting
 - [ ] Replace old op tracker with new tracker (#295)
 - [ ] Replace boolean `EventLoopPendingState` with "global" counters for faster eval
 - [ ] Skip scope for op dispatch where possible (we have a new, fast function for dispatch)
 - [ ] Remove event middlewares entirely from event loop when not used
